"""create_user_table

Revision ID: 8ae4ef6c3c84
Revises: 436b093d3960
Create Date: 2024-08-22 23:15:09.408928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae4ef6c3c84'
down_revision: Union[str, None] = '436b093d3960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('name', sa.String(), nullable=True, comment='Имя пользователя'),
    sa.Column('hashed_password', sa.String(), nullable=True, comment='Хешированный пароль'),
    sa.Column('role_id', sa.UUID(), nullable=True, comment='Идентификатор роли пользователя'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата регистрации'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
