"""create_defect_table

Revision ID: 0d683226308f
Revises: 88593a2c2db9
Create Date: 2024-08-22 22:56:49.637197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d683226308f'
down_revision: Union[str, None] = '88593a2c2db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор дефекта'),
    sa.Column('x_coord', sa.Integer(), nullable=False, comment='Координата по оси X'),
    sa.Column(
        'continue_for',
        sa.Integer(),
        nullable=False,
        comment='Количество таких же дефектов справа по оси X',
        default=0
    ),
    sa.Column('type_id', sa.UUID(), nullable=False, comment='Идентификатор типа дефекта'),
    sa.ForeignKeyConstraint(['type_id'], ['defect_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defect')
    # ### end Alembic commands ###
