"""create_defect_type_table

Revision ID: 3e6c5e71a4db
Revises: 
Create Date: 2024-08-22 22:55:51.454503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6c5e71a4db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_type',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор типа дефекта'),
    sa.Column('name', sa.String(), nullable=False, comment='Название типа дефекта'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defect_type')
    # ### end Alembic commands ###
