"""create_structural_unit_type_table

Revision ID: 5183d8003581
Revises: 3e6c5e71a4db
Create Date: 2024-08-22 22:56:16.105999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5183d8003581'
down_revision: Union[str, None] = '3e6c5e71a4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structural_unit_type',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор типа структорного элемента'),
    sa.Column('name', sa.String(), nullable=False, comment='Название типа структурного элемента'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structural_unit_type')
    # ### end Alembic commands ###
