"""create_structural_unit_table

Revision ID: 8ed740b6416c
Revises: 0d683226308f
Create Date: 2024-08-22 22:57:13.145987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed740b6416c'
down_revision: Union[str, None] = '0d683226308f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structural_unit',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор структурного элемента'),
    sa.Column('type_id', sa.UUID(), nullable=False, comment='Идентификатор типа структурного элемента'),
    sa.Column('x_coord', sa.Integer(), nullable=False, comment='Координата по оси X'),
    sa.Column(
        'continue_for',
        sa.Integer(),
        nullable=False,
        comment='Количество таких же структурных элементов справа по оси X',
        default=0
    ),
    sa.ForeignKeyConstraint(['type_id'], ['structural_unit_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structural_unit')
    # ### end Alembic commands ###
