"""create_magnetogram_defect_table

Revision ID: 4218af1645d4
Revises: f0a9def49ad1
Create Date: 2024-08-22 22:57:36.552870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4218af1645d4'
down_revision: Union[str, None] = 'f0a9def49ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magnetogram_defect',
    sa.Column('id', sa.UUID(), nullable=False, comment='Идентификатор связи'),
    sa.Column('magnetogram_id', sa.UUID(), nullable=True, comment='Идентификатор магнитограммы'),
    sa.Column('defect_id', sa.UUID(), nullable=True, comment='Идентификатор дефекта'),
    sa.ForeignKeyConstraint(['magnetogram_id'], ['magnetogram.id'], ),
    sa.ForeignKeyConstraint(['defect_id'], ['defect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magnetogram_defect')
    # ### end Alembic commands ###
